# Generated by Django 4.2.4 on 2023-08-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="distance",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
