# Generated by Django 4.2.4 on 2023-08-09 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0002_route_distance"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="airplane",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flights",
                to="airport.airplane",
            ),
            preserve_default=False,
        ),
    ]
