# Generated by Django 4.2.4 on 2023-08-10 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0003_flight_airplane"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airplane",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="airplanetype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="airport",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="crew",
            options={"ordering": ["first_name"]},
        ),
        migrations.AlterModelOptions(
            name="flight",
            options={"ordering": ["departure_time"]},
        ),
        migrations.AlterModelOptions(
            name="route",
            options={"ordering": ["source"]},
        ),
    ]
