# Generated by Django 4.2.4 on 2023-08-10 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0004_alter_airplane_options_alter_airplanetype_options_and_more"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["user"]},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat"]},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("flight", "row", "seat")},
        ),
    ]
